app/models.py
from app import db
from flask_login import UserMixin
from app import login


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(50), nullable=False)
    password_hash = db.Column(db.String(128))
    kanbans = db.relationship('Kanban')

    def __repr__(self):
        return f"user: {self.nickname}"


class Kanban(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    uid = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    type = db.Column(db.Integer, nullable=False)
    content = db.Column(db.Text, nullable=False)
    create_time = db.Column(db.DateTime, nullable=False)

    def __repr__(self):
        return f"kanban: id = {self.id},\n\
                 uid = {self.uid}\n\
                 type = {self.type}\n"


@login.user_loader
def load_user(id):
    return User.query.get(int(id))

app/__init__.py
from flask import Flask
from .config import Config
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")

    return app

app/auth.py
from flask import Blueprint, render_template, request, url_for, flash, redirect
from flask_login import current_user, login_user, logout_user
from .models import User
from werkzeug.security import check_password_hash, generate_password_hash
from . import db

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('views.board'))
    if request.method == "POST":
        email = request.form.get("user_email")
        password = request.form.get("user_password")

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password_hash, password):
                flash("Logged in succsessfully!", category="success")
                login_user(user)
                return redirect(url_for("views.board"))
            else:
                flash("Incorrect password, try again.", category="error")
        else:
            flash("Email does not exist.", category="error")

    return render_template("login.html")


@auth.route("/logout", methods=["GET", "POST"])
def logout():
    if not current_user.is_authenticated:
        return redirect(url_for('auth.login'))

    logout_user()
    return redirect(url_for("auth.login"))


@auth.route("/sign_up", methods=["GET", "POST"])
def sign_up():
    if request.method == "POST":
        email = request.form.get("user_email")
        password = request.form.get("user_password")
        password1 = request.form.get("user_password1")

        user = User.query.filter_by(email=email).first()
        if user:
            flash("Email already exists.", category="error")
        elif len(email) < 4:
            flash("Email must be greater than 3 characters.", category="error")
        elif password != password1:
            flash("Passwords don\"t match.", category="error")
        elif len(password) < 6:
            flash("Password must be at least 6 characters.", category="error")
        else:
            new_user = User(email=email, password_hash=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            flash('Account created!', category='success')
            return render_template("login.html")

    return render_template("sign_up.html")

app/views.py
from flask import Blueprint
from flask import redirect, url_for, request
from flask import render_template
from flask_login import current_user
from app import db
from datetime import datetime
from .models import User, Kanban

views = Blueprint("views", __name__)


@views.route("/")
def home():
    return redirect(url_for("auth.login"))


@views.route("/board")
def board():
    if not current_user.is_authenticated:
        return redirect(url_for("auth.login"))
    
    user = User.query.filter_by(email=current_user.email, 
            password_hash=current_user.password_hash).first()
    

    if user:
        todos = Kanban.query.filter_by(uid=user.id, type=0)
        inprogs = Kanban.query.filter_by(uid=user.id, type=1)
        dones = Kanban.query.filter_by(uid=user.id, type=2)
    
        return render_template("board.html", todos=todos, inprogs=inprogs, dones=dones)

    return render_template("board.html")

@views.route("/add_kanban", methods=["GET", "POST"])
def add_kanban():
    if not current_user.is_authenticated:
        return redirect(url_for("auth.login"))
    
    user = User.query.filter_by(email=current_user.email, 
            password_hash=current_user.password_hash).first()
    
    if user:
        if request.method == "POST":
            kb_text = request.form.get("new_kanban")

            if kb_text == "":
                return redirect(url_for("views.board"))

            kb_type = request.form.get("kb_type")
            
            if kb_type not in ("to_do", "in_progress", "done"):
                return redirect(url_for("views.board"))

            kb_type = ("to_do", "in_progress", "done").index(kb_type)

            new_kanban = Kanban(uid=current_user.id,
                    type=kb_type, content=kb_text, create_time=datetime.now())
            db.session.add(new_kanban)
            db.session.commit()

    return redirect(url_for("views.board"))

@views.route("/delete_kanban/<id>", methods=["GET", "POST"])
def delete_kanban(id):
    if not current_user.is_authenticated:
        return redirect(url_for("auth.login"))

    kanban = Kanban.query.filter_by(id=id).first()

    if kanban:
        db.session.delete(kanban)
        db.session.commit()

    return redirect(url_for("views.board"))

app/templates/base.html
<!doctype html>

<html>
	<head>
		<meta charset="utf-8">
		<link href="{{ url_for('static', filename='index.css') }}" rel="stylesheet" type="text/css">
		<title>Kanban Web</title>

		<style>
			form {
			/* Center the form on the page */
				/*margin: 0 auto;*/
				width: 42%;
				/* Form outline */
				padding: 1em;
				/*border: 1px solid #CCC;*/
				border-radius: 1em;
			}

			label {
				/* Uniform size & alignment */
				display: inline-block;
				width: 115px;
				text-align: right;
			}

			input,
			textarea {
				/* To make sure that all text fields have the same font settings
				By default, textareas have a monospace font */
				font: 1em sans-serif;

				/* Uniform text field size */
				width: 300px;
				height: 50px;
				box-sizing: border-box;
				padding-left: 10px;

				/* Match form field borders */
				border: 1px solid #999;
				border-radius: 2em;
				position: relative;
				caret-color: transparent;
			}

			input:focus,
			textarea:focus {
				/* Additional highlight for focused elements */
				border-color: #000;
			}

			ul {
				list-style: none;
				padding: 0;
				margin: 0;
			}

			li {
				margin: 1em;
			}
		</style>
	</head>
	<body>
		<div class="table">
		    <div class="tr">
		        <div class="d1">KAN</div>
		        <div class="d2">BAN</div>
		        <div class="d3">WEB</div>
		    </div>
		</div>
		
		{% block content %}{% endblock %}
	</body>
</html>

app/templates/board.html
<!doctype html>

<html>
	<head>
		<meta charset="utf-8">
		<link href="{{ url_for('static', filename='board.css') }}" rel="stylesheet" type="text/css">
		<title>Kanban Web - Board</title>
	</head>
	<body>
		<div class="table">
		    <div class="tr">
		        <div class="d1">KanBan Web</div>
		        <div class="d2"></div>
		        <div class="d3">{{current_user.email}}    <a href="{{ url_for('auth.logout') }}">Log out</a></div>
		    </div>
		</div>
		
		Hello, {{current_user.email}}!

		<div class="table">
		    <div class="tr">
		        <div class="kb1"></div>
		        <div class="kb2">
		        	<form action="add_kanban" method="POST">
			        	<input type="text" id="new_kb" name="new_kanban">
			        	<button class="favorite styled" type="submit" name="kb_type" value="to_do">TO DO</button>
			        	<button class="favorite styled" type="submit" name="kb_type" value="in_progress">IN PROGRESS</button>
			        	<button class="favorite styled" type="submit" name="kb_type" value="done">DONE</button>
		        	<form>
		        </div>
		        <div class="kb3"></div>
		    </div>
		</div>
		<br>
		<div class="table">
		    <div class="tr">
		        <div class="kb1">
		        TO DO

		        {% for todo in todos %}
			    <p>
			    <sup><a href="{{ url_for('views.delete_kanban', id=todo.id|string) }}">X</a></sup>{{ todo.content }}
			    </p>
			    {% endfor %}
		    	</div>

		        <div class="kb2">
		        IN PROGRESS

		        {% for inprog in inprogs %}
			    <p>
			    <sup><a href="{{ url_for('views.delete_kanban', id=inprog.id|string) }}">X</a></sup>{{ inprog.content }}
			    </p>
			    {% endfor %}
		    	</div>

		        <div class="kb3">
		        DONE

		        {% for done in dones %}
			    <p>
			    <sup><a href="{{ url_for('views.delete_kanban', id=done.id|string) }}">X</a></sup>{{ done.content }}
			    </p>
			    {% endfor %}
		    	</div>
		    </div>
		</div>
	</body>
</html>

app/templates/login.html
{% extends "base.html" %}

{%block content %}
<div class="center">
    <form class="center" method="post">
        <ul>
            <li>
                <input type="text" id="email" name="user_email" placeholder="Email">
            </li>
            <li>
                <input type="password" id="password" name="user_password" placeholder="Password">
            </li>
            <li class="button">
                <div class="table">
                    <div class="tr">
                        <div class="d1">
                            <button class="favorite styled" type="submit">Log in</button>
                        </div>
                        <div class="d2"></div>
                        <div class="d3">
                            <a href="{{ url_for('auth.sign_up') }}">
                                Register
                            </a>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    <form>
</div>
{% endblock %}

app/templates/sign_up.html
{% extends "base.html" %}

{%block content %}
<div class="center">
    <form class="center" method="post">
        <ul>
            <li>
                <input type="text" id="email" name="user_email" placeholder="Email">
            </li>
            <li>
                <input type="password" id="password" name="user_password" placeholder="Password">
            </li>
            <li>
                <input type="password" id="password1" name="user_password1" placeholder="Repeat Password">
            </li>
            <li class="button">
                <div class="table">
                    <div class="tr">
                        <div class="d1"></div>
                        <div class="d2">
                            <button class="favorite styled" type="submit">Sign Up</button>
                        </div>
                        <div class="d3"></div>
                    </div>
                </div>
            </li>
        </ul>
    <form>
</div>
{% endblock %}